# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
books = [
  {name: "1984", description: "While 1984 has come and gone, Orwell's narrative is more timely than ever. 1984 presents a negative utopia, that is at once a startling and haunting vision of the world — so powerful that it's completely convincing from start to finish. No one can deny the power of this novel, its hold on the imaginations of entire generations of readers, or the resiliency of its admonitions — a legacy that seems to grow, not lessen, with the passage of time.", author: "George Orwell, Erich Fromm"},
  {name: "The Catcher in the Rye", description: "Since his debut in 1951 as The Catcher in the Rye, Holden Caulfield has been synonymous with cynical adolescent. Holden narrates the story of a couple of days in his sixteen-year-old life, just after he's been expelled from prep school, in a slang that sounds edgy even today and keeps this novel on banned book lists. It begins: If you really want to hear about it, the first thing you'll probably want to know is where I was born and what my lousy childhood was like, and how my parents were occupied and all before they had me, and all that David Copperfield kind of crap, but I don't feel like going into it, if you want to know the truth. In the first place, that stuff bores me, and in the second place, my parents would have about two hemorrhages apiece if I told anything pretty personal about them.", author: "J.D. Salinger"},
  {name: "The Great Gatsby", description: "A portrait of the Jazz Age in all of its decadence and excess, The Great Gatsby captured the spirit of the author's generation and earned itself a permanent place in American mythology. Self-made, self-invented millionaire Jay Gatsby embodies some of Fitzgerald's--and his country's--most abiding obsessions: money, ambition, greed, and the promise of new beginnings. Gatsby believed in the green light, the orgiastic future that year by year recedes before us. It eluded us then, but that's no matter--tomorrow we will run faster, stretch out our arms farther.... And one fine morning--Gatsby's rise to glory and eventual fall from grace becomes a kind of cautionary tale about the American Dream.", author: "F. Scott Fitzgerald"},
  {name: "The Diary of a Young Girl", description: "Discovered in the attic in which she spent the last years of her life, Anne Frank's remarkable diary has since become a world classic—a powerful reminder of the horrors of war and an eloquent testament to the human spirit. In 1942, with Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, they and another family lived cloistered in the Secret Annexe of an old office building. Cut off from the outside world, they faced hunger, boredom, the constant cruelties of living in confined quarters, and the ever-present threat of discovery and death.", author: "Anne Frank, Eleanor Roosevelt"},
  {name: "Brave New World", description: "Far in the future, the World Controllers have created the ideal society. Through clever use of genetic engineering, brainwashing and recreational sex and drugs, all its members are happy consumers. Bernard Marx seems alone harbouring an ill-defined longing to break free. A visit to one of the few remaining Savage Reservations, where the old, imperfect life still continues, may be the cure for his distress..", author: "Aldous Huxley"},
  {name: "East of Eden", description: "Set in the rich farmland of California’s Salinas Valley, this sprawling and often brutal novel follows the intertwined destinies of two families—the Trasks and the Hamiltons—whose generations helplessly reenact the fall of Adam and Eve and the poisonous rivalry of Cain and Abel. Here Steinbeck created some of his most memorable characters and explored his most enduring themes: the mystery of identity; the inexplicability of love; and the murderous consequences of love’s absence.", author: "John Steinbeck"},
  {name: "The Old Man and the Sea", description: "Here, for a change, is a fish tale that actually does honor to the author. The Old Man & the Sea revived Hemingway's career, which was foundering under the weight of such postwar stinkers as Across the River & into the Trees. It also led directly to his receipt of the 1954 Nobel Prize--an award he gladly accepted, despite his earlier observation that no son of a bitch that ever won the Nobel Prize ever wrote anything worth reading afterwards", author: "Ernest Hemingway"},
  {name: "Atlas Shrugged", description: "You must be prepared, when you read this novel, to check every premise at the root of your convictions. This is a mystery story, not about the murder — and rebirth — of man’s spirit. It is a philosophical revolution, told in the form of an action thriller of violent events, a ruthlessly brilliant plot structure and an irresistible suspense. Do you say this is impossible? Well, that is the first of your premises to check.", author: "Ayn Rand"},
  {name: "The Alchemist", description: "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and inspiring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself king, and an alchemist, all of whom point Santiago in the direction of his quest. No one knows what the treasure is, or if Santiago will be able to surmount the obstacles along the way. But what starts out as a journey to find worldly goods turns into a discovery of the treasure found within. Lush, evocative, and deeply humane, the story of Santiago is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.", author: "Paulo Coelho"},
  {name: "The Unbearable Lightness of Being", description: "In The Unbearable Lightness of Being, Milan Kundera tells the story of a young woman in love with a man torn between his love for her and his incorrigible womanizing and one of his mistresses and her humbly faithful lover. This magnificent novel juxtaposes geographically distant places, brilliant and playful reflections, and a variety of styles to take its place as perhaps the major achievement of one of the world’s truly great writers", author: "Milan Kundera, Michael Henry Heim"},
  {name: "The Metamorphosis", description: "It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing -- though absurdly comic -- meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction.", author: "Franz Kafka, Stanley Corngold"},
  {name: "The Master and Margarita", description: "Mikhail Bulgakov's devastating satire of Soviet life was written during the darkest period of Stalin's regime. Combining two distinct yet interwoven parts—one set in ancient Jerusalem, one in contemporary Moscow—the novel veers from moods of wild theatricality with violent storms, vampire attacks, and a Satanic ball; to such somber scenes as the meeting of Pilate and Yeshua, and the murder of Judas in the moonlit garden of Gethsemane; to the substanceless, circus-like reality of Moscow. Its central characters, Woland (Satan) and his retinue—including the vodka-drinking black cat, Behemoth; the poet, Ivan Homeless; Pontius Pilate; and a writer known only as The Master, and his passionate companion, Margarita—exist in a world that blends fantasy and chilling realism, an artful collage of grotesqueries, dark comedy, and timeless ethical questions.", author: "Mikhail Bulgakov"},
  {name: "Beyond the ice limit", description: "Effective Engineering Solutions’ chief honcho, Eli Glinn, is out of his wheelchair, walking and ready for revenge after his agent Gideon Crew discovered a 'restorative, health-giving lotus’ on his last adventure (The Lost Island, 2014, etc.).Years ago, Glinn was nearly killed (thus the wheelchair) when his ship, the Rolvaag, sank two miles below the sea in the Hesperides Deep near the South Pole ice limit. The Rolvaag was transporting a 25,000 ton meteorite—'the largest meteorite in the world'—that EES had been paid to remove from nearby Isla Desolación by billionaire Palmer Lloyd. Now Glinn has learned the sunken meteorite has begun to grow into a treelike form, nicknamed 'the Baobab' because of its shape. Glinn believes it’s an extraterrestrial life form, an alien seed that will destroy the Earth. He wants Crew to destroy it with a nuclear device. Thus begins relentless mayhem, another thrill-a-minute read. Piloting a Deep Submergence Vehicle, Crew snips a piece of Baobab. Aboard ship, the segment mutates into wormlike creatures that drill through the nasal passages and into the brains of sleeping crew, who thereafter run amok at Baobab’s bidding. Series readers will see a new side of the enigmatic Glinn. Crew remains the standard angst-driven hero. There’s the requisite slovenly, boorish, yet brilliant computer genius and a less memorable supporting cast. New readers will struggle with minimal references to EES’s raison d'être and its fabled Quantitative Behavior Analysis. There’s diving lore, a précis on assembling a nuke, and a short, dense dissection of 'endoplasmic reticulum' and 'Golgi bodies' to conjecture a 'carbon-hydrogen-silicon-oxygen form of life' that seems to have no purpose other than the biological imperative.Science fiction as action adventure, the sort of book primed for screen treatment if a producer can find a sufficient F/X budget.", author: "Douglas Preston"}
]

books.each do |book|
  Book.create book
end

reviews = [
  {text: "1984 is not a particularly good novel, but it is a very good essay. On the novel front, the characters are bland and you only care about them because of the awful things they live through. As a novel all the political exposition is heavyhanded, and the message completely overrides any sense of storytelling. As an essay, the points it makes can be earthshaking. It seems everyone who has so much as gotten a parking ticket thinks he lives in a 1984-dystopia. Every administration that reaches for power, injures civil liberties or collaborates too much with media is accused of playing Big Brother. These are the successes of 1984's paranoia, far outliving its original intent as a battery against where Communism was going (Orwell was a severely disappointed Marxist), and while people who compare their leaders to Big Brother are usually overreaching themselves and speak far away from Orwell's intent and vision, it is a useful catchcloth for dissent. Like so many immortalized books with a social vision, 1984's actual substance is so thin that its ideologies and fear-mongering aspects can be stretched and skewed to suit the readers. If you'd like a better sense of the real world and Orwell's intents, rather than third-hand interpretations of his fiction, then his Homage to Catalonia is highly recommended.", author: "John Wiswell", book_id: 1},
  {text: "In George Orwell's 1984, Winston Smith is an open source developer who writes his code offline because his ISP has installed packet sniffers that are regulated by the government under the Patriot Act. It's really for his own protection, though. From, like, terrorists and DVD pirates and stuff. Like every good American, he drinks Coca-Cola and his processed food has desensitized his palate to all but four flavors: sweet, salty-so-that-you-will-drink-more-coca-cola, sweet, and Cooler Ranch!(tm). His benevolent overlords have provided him with some war happening somewhere for some reason so that he, and the rest of the population, can be sure that the government is really in his best interests. In fact, the news always has some story about Paris Hilton or yet another white girl who has been abducted by some evil bastard who is biologically wired by 200,000 years of human evolution to fuck 12-year-olds, but is socially conditioned to be obsessed with sex, yet also to feel guilty about it. This culminates into a distorted view of sexuality, and results in rape and murder, which both make for very good news topics. This, too, is in Winston's best interests because, while fear is healthy, thinking *too* much about his own mortality is strictly taboo, as it may lead to something dangerously insightful, and he might lose his taste for Coca Cola and breast implants. The television also plays on his fears of the unknown by exaggerating stereotypes of minorities and homosexuals, under the guise of celebrating ‘diversity', but even these images of being ghetto-fabulous and a lisping interior designer actually exist solely to promote racism and homophobia, which also prove to be efficient distractions.", author: Dave, book_id: 1},
  {text: "WAR IS PEACE. FREEDOM IS SLAVERY. IGNORANCE IS STRENGTH. Those words keep sounding in my head since I read this book. Gosh, probably the most haunting not to mention frightening book I've ever read. 1984 should also be included in the horror genre.", author: "Silvana", book_id: 1},
  {text: "I was worried as hell about reading this book again. The last time I read it was about a thousand years ago when I was just a kid. I was lousy with angst just like good old Holden back then. I really was. Now that I’m a crummy old guy I figured that I wouldn’t like it anymore. That’s the one thing about crummy old guys, they always hate books that kids like. Every time I reread a corny book that I really liked when I was a kid it makes me want to give the writer a buzz and ask what the hell is going on. It’s like they are trying to give you the time in the back of a cab when you don’t feel like getting the time at all. It’s damn depressing, I swear to God it is. If you want to know the truth, you probably couldn’t even talk to a phony writer on the phone. You would just end up talking to his butler or some snobbish person like that and asking if they would give the writer your message. He probably wouldn’t even do it. The thing with guys like that is that they will never give writers your messages. That’s something that annoys the hell out of me. Turns out this is still a damn good book. Salinger kid is a great writer. He really is", author: "Matt", book_id: 2},
  {text: "Beautiful! I had been somewhat hesitant to read 'The Catcher in the Rye' after snoozing through Salinger's 'Nine Stories', but I'm glad I finally came around. This book is a work of genius.", author: "Jason", book_id: 2},
  {text: "In a word, The Great Gatsby is about deception; Fitzgerald tints our glasses rosy with gorgeous prose and a narrator you want so much to trust, but leaves the lenses just translucent enough for us to see that Gatsby is getting the same treatment. And if Gatsby represents the truth of the American Dream, it means trouble for us all. Consider it the most pleasant insult you'll ever receive.", author: "Alex", book_id: 3},
  {text: "Classic. Yes. THE great American novel. Hmph, so I heard. I suppose it should make one more interested, or at least feel more compelled to read something (or re-read as is the case here) when it has "classic" and "everyone else loves it!" stamped all over it. And has a movie made out of it, though what beloved novel hasn't these days? Of course, I originally read FSF's Gatsby because I was expected to for a high school English class. So, even though I was never the type to do homework, I read The Great Gatsby because it had a neat cover, Fitzgerald is fun to say, and, of course, the legend of Zelda.", author: "Kat", book_id: 3},
  {text: "Great Gatsby is a beautiful story. Fitzgerald's symbolism is deep and profound. I believe that for every reader this story of love and loss has something different to say. It touches the heart in so many different ways. For me it is a story about ambition, dreams and how much we would give away in order to fulfill our deepest desires. Every person has a green light in the distance. Every person is trying to reach something behind the mist. Great Gatsby is a beautiful book. A must read, without a doubt. It definitely touched my heart. ", author: "Richard", book_id: 3},
  {text: "I read this book when I was about 8 and then again when I was 14. I think that it is good 8 and up.", author: "Caroline", book_id: 4},
  {text: "I really loved this! I read it in sixth grade and it has really good role models and messages.", author: "Brat", book_id: 4},
  {text: "Brave New World is a classic written to make its readers uncomfortable. It accomplishes its point well. Still, it is only getting 3 stars from me, as I rate books based on my personal level of enjoyment rather than literary value.", author: "Nataliya", book_id: 5},
  {text: "Such a happy tale. Now I remember why I don't read dystopia all that often, it's depressing. I liked this novel but I do think it's the weakest out of the Big Dystopia 3 (the other two being Nineteen Eighty-Four and Fahrenheit 451). I'd recommend it on the basis of just how innovative and subversive this novel really is, along with a good plot and an interesting world", author: "Barry", book_id: 5},
  {text: "To cut a long story short, the inescapable destiny of every society is to morph into a dystopia. Alternatively, a biting satire on capitalism and consumerism.", author: "Samanta", book_id: 5},
  {text: "I am on a golden roll of amazingly fantastic books!! East of Eden by John Steinbeck was our book club pick for this month. I almost didn't read it. You see, it's an old friend...and I ALMOST didn't re-read it... and that would have been tragic.", author: "Kristin", book_id: 6},
  {text: "Parts of this book are god-like. At different stages in the beginning, middle, and end, I burnt through pages like this was some sort of mystery-thriller, but obviously with all the depth of Steinbeck...", author: "Brian", book_id: 6},
  {text: "I think this is the best-known story in the world because it is everybody's story. I think it is the symbol story of the human soul. ...The greatest terror a child can have is that he is not loved, and rejection is the hell he fears. I think everyone in the world to a large or small extent has felt rejection. And with rejection comes anger, and with anger some kind of crime in revenge for the rejection, and with the crime guilt - and that is the story of mankind.", author: "Madeline", book_id: 6},
  {text: "There isn't any symbolism. The sea is the sea. The old man is an old man. The boy is a boy and the fish is a fish. The sharks are all sharks no better and no worse. All the symbolism that people say is shit. What goes beyond is what you see beyond when you know.", author: "Madeline", book_id: 7},
  {text: "Sad book. Read it, but know it is sad. This is probably written at about a 4th grade reading level, and the audience is at least that broad.", author: "Greg", book_id: 7},
  {text: "I don't know if any other author would have been able to spend 140 pages on a subject as simple as this (although Dickens probably could), but Ernest Hemingway succeeded in the attempt, creating a timeless classic. The language is not very demanding - sometimes even poor, if you look at the way he repeats himself unnecessarily at passages every writing adviser would cringe at. And yet there is something powerful, endearing behind those words, something which lures you in without you even realizing it. It is impossible to describe the atmosphere within this tale. Read it for yourself if you are open for classics without a lot of action going on - and this is a short one, a story I read in the course of two hours with interruptions - or don't if you need your complex plots. For everyone else, I'd highly recommend it.", author: "Robert", book_id: 7},
  {text: "This book, as much as I detest it, is actually rather useful. Those who have read it tend to be those whom I most especially desire to avoid. Because those who have read it are invariably proud of the fact--ostentatiously so--it is even easier for me to keep my life free and clear of delusional egomaniacs. Thank you Ayn Rand.", author: "Seth", book_id: 8},
  {text: "Based on everything I've heard about Rand, in conversation and online, from her supporters and her detractors, or in interviews with the author or articles by her, I feel there is no reason to believe that this book or any of her others contain anything that is worth reading, not even as 'cautionary example'. Nothing about it sounds the least bit appealing or reasone", author: "Kelly", book_id: 8},
  {text: "'When you really want something, the whole universe conspires in helping you to achieve it' This book has crossed the boundaries of books, and has taken a life of its own, creating a movement all around the globe.", author: "Nikita", book_id: 9},
  {text: "This book definitely wins the award for Most Pretentious Title Ever", author: "Tom", book_id: 10},
  {text: "13% and I'm done. I have had a run of books that have bored me, or annoyed me, or just did nothing for me. This one is... You know, I don't even know how to describe this one.", author: "Jess", book_id: 10},
  {text: "I spent part of my lazy weekend reading this book on the grassy hills of The Huntington Library surrounded by gardens, art, and beauty. Even the serene surroundings and my sensational reading date could not make up for this book. Weak characters, horrible assumptions, pseudo philosophy, and no clear grasp of how women are actually motivated. Only wannabe Lotharios who pride themselves as philosophers would enjoy this. I tried. I really did.", author: "Anton", book_id: 10},
  {text: "Far be it from me to analyze this unique work from Kafka. He never explained it himself, so we are free to make of it what we will.", author: "Peter", book_id: 11},
  {text: "A classic story, and one of my favorites by Kafka. I re-read this one yesterday, and all of the emotions that I felt the first time I discovered this title, immediately came flooding back. A strange tale--but one that won't leave your mind soon afterwards.", author: "Kristina", book_id: 11},
  {text: "I had vivid memories of the first reading, although if you had asked me to describe them, I wouldn’t have been able to. All I can recall is something fluid and magical.", author: "Albert", book_id: 12},
  {text: "Re-reading can be a terribly useful practice. I enjoyed the book enough before I suppose, but not nearly so much as this time.", author: "John", book_id: 12},
  {text: "I enjoyed Beyond The Ice Limit, and finished it in two days. I've read virtually all of these authors' books -- their stand-alones, partnered and individual stories -- the Gideon series are their current shining stars in this girl's opinion. I appreciated that this is a sequel to their earlier Ice Limit story, although it can be read on its own with pleasure. I enjoyed the way the authors found to weave Gideon into the follow-up story, even though he wasn't been involved in the first Ice Limit story. Good entertainment, loved the supernatural element and the way Preston / Child wrapped the story up.", author: "Frank", book_id: 13},
  {text: "There is nothing, as far as my opinion goes, as fine as reading a new book by Preston and Child. This is no exception!! If you love Crew this one is for you. I will not go into much except to say yes it is a sequel but it is a stand alone novel as well. Great read and as usual I could not put it down!!", author: "Kate", book_id: 13},
]

reviews.each do |review|
  Review.create review
end
