# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
books = [
  {name: "1984", description: "While 1984 has come and gone, Orwell's narrative is more timely than ever. 1984 presents a negative utopia, that is at once a startling and haunting vision of the world — so powerful that it's completely convincing from start to finish. No one can deny the power of this novel, its hold on the imaginations of entire generations of readers, or the resiliency of its admonitions — a legacy that seems to grow, not lessen, with the passage of time.", author: "George Orwell, Erich Fromm"},
  {name: "The Catcher in the Rye", description: "Since his debut in 1951 as The Catcher in the Rye, Holden Caulfield has been synonymous with cynical adolescent. Holden narrates the story of a couple of days in his sixteen-year-old life, just after he's been expelled from prep school, in a slang that sounds edgy even today and keeps this novel on banned book lists. It begins: If you really want to hear about it, the first thing you'll probably want to know is where I was born and what my lousy childhood was like, and how my parents were occupied and all before they had me, and all that David Copperfield kind of crap, but I don't feel like going into it, if you want to know the truth. In the first place, that stuff bores me, and in the second place, my parents would have about two hemorrhages apiece if I told anything pretty personal about them.", author: "J.D. Salinger"},
  {name: "The Great Gatsby", description: "A portrait of the Jazz Age in all of its decadence and excess, The Great Gatsby captured the spirit of the author's generation and earned itself a permanent place in American mythology. Self-made, self-invented millionaire Jay Gatsby embodies some of Fitzgerald's--and his country's--most abiding obsessions: money, ambition, greed, and the promise of new beginnings. Gatsby believed in the green light, the orgiastic future that year by year recedes before us. It eluded us then, but that's no matter--tomorrow we will run faster, stretch out our arms farther.... And one fine morning--Gatsby's rise to glory and eventual fall from grace becomes a kind of cautionary tale about the American Dream.", author: "F. Scott Fitzgerald"},
  {name: "The Diary of a Young Girl", description: "Discovered in the attic in which she spent the last years of her life, Anne Frank's remarkable diary has since become a world classic—a powerful reminder of the horrors of war and an eloquent testament to the human spirit. In 1942, with Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, they and another family lived cloistered in the Secret Annexe of an old office building. Cut off from the outside world, they faced hunger, boredom, the constant cruelties of living in confined quarters, and the ever-present threat of discovery and death.", author: "Anne Frank, Eleanor Roosevelt"},
  {name: "Brave New World", description: "Far in the future, the World Controllers have created the ideal society. Through clever use of genetic engineering, brainwashing and recreational sex and drugs, all its members are happy consumers. Bernard Marx seems alone harbouring an ill-defined longing to break free. A visit to one of the few remaining Savage Reservations, where the old, imperfect life still continues, may be the cure for his distress..", author: "Aldous Huxley"},
  {name: "East of Eden", description: "Set in the rich farmland of California’s Salinas Valley, this sprawling and often brutal novel follows the intertwined destinies of two families—the Trasks and the Hamiltons—whose generations helplessly reenact the fall of Adam and Eve and the poisonous rivalry of Cain and Abel. Here Steinbeck created some of his most memorable characters and explored his most enduring themes: the mystery of identity; the inexplicability of love; and the murderous consequences of love’s absence.", author: "John Steinbeck"},
  {name: "The Old Man and the Sea", description: "Here, for a change, is a fish tale that actually does honor to the author. The Old Man & the Sea revived Hemingway's career, which was foundering under the weight of such postwar stinkers as Across the River & into the Trees. It also led directly to his receipt of the 1954 Nobel Prize--an award he gladly accepted, despite his earlier observation that no son of a bitch that ever won the Nobel Prize ever wrote anything worth reading afterwards", author: "Ernest Hemingway"},
  {name: "Atlas Shrugged", description: "You must be prepared, when you read this novel, to check every premise at the root of your convictions. This is a mystery story, not about the murder — and rebirth — of man’s spirit. It is a philosophical revolution, told in the form of an action thriller of violent events, a ruthlessly brilliant plot structure and an irresistible suspense. Do you say this is impossible? Well, that is the first of your premises to check.", author: "Ayn Rand"},
  {name: "The Alchemist", description: "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and inspiring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself king, and an alchemist, all of whom point Santiago in the direction of his quest. No one knows what the treasure is, or if Santiago will be able to surmount the obstacles along the way. But what starts out as a journey to find worldly goods turns into a discovery of the treasure found within. Lush, evocative, and deeply humane, the story of Santiago is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.", author: "Paulo Coelho"},
  {name: "The Unbearable Lightness of Being", description: "In The Unbearable Lightness of Being, Milan Kundera tells the story of a young woman in love with a man torn between his love for her and his incorrigible womanizing and one of his mistresses and her humbly faithful lover. This magnificent novel juxtaposes geographically distant places, brilliant and playful reflections, and a variety of styles to take its place as perhaps the major achievement of one of the world’s truly great writers", author: "Milan Kundera, Michael Henry Heim"},
  {name: "The Metamorphosis", description: "It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing -- though absurdly comic -- meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction.", author: "Franz Kafka, Stanley Corngold"},
  {name: "The Master and Margarita", description: "Mikhail Bulgakov's devastating satire of Soviet life was written during the darkest period of Stalin's regime. Combining two distinct yet interwoven parts—one set in ancient Jerusalem, one in contemporary Moscow—the novel veers from moods of wild theatricality with violent storms, vampire attacks, and a Satanic ball; to such somber scenes as the meeting of Pilate and Yeshua, and the murder of Judas in the moonlit garden of Gethsemane; to the substanceless, circus-like reality of Moscow. Its central characters, Woland (Satan) and his retinue—including the vodka-drinking black cat, Behemoth; the poet, Ivan Homeless; Pontius Pilate; and a writer known only as The Master, and his passionate companion, Margarita—exist in a world that blends fantasy and chilling realism, an artful collage of grotesqueries, dark comedy, and timeless ethical questions.", author: "Mikhail Bulgakov"},
  {name: "Beyond the ice limit", description: "Effective Engineering Solutions’ chief honcho, Eli Glinn, is out of his wheelchair, walking and ready for revenge after his agent Gideon Crew discovered a 'restorative, health-giving lotus’ on his last adventure (The Lost Island, 2014, etc.).Years ago, Glinn was nearly killed (thus the wheelchair) when his ship, the Rolvaag, sank two miles below the sea in the Hesperides Deep near the South Pole ice limit. The Rolvaag was transporting a 25,000 ton meteorite—'the largest meteorite in the world'—that EES had been paid to remove from nearby Isla Desolación by billionaire Palmer Lloyd. Now Glinn has learned the sunken meteorite has begun to grow into a treelike form, nicknamed 'the Baobab' because of its shape. Glinn believes it’s an extraterrestrial life form, an alien seed that will destroy the Earth. He wants Crew to destroy it with a nuclear device. Thus begins relentless mayhem, another thrill-a-minute read. Piloting a Deep Submergence Vehicle, Crew snips a piece of Baobab. Aboard ship, the segment mutates into wormlike creatures that drill through the nasal passages and into the brains of sleeping crew, who thereafter run amok at Baobab’s bidding. Series readers will see a new side of the enigmatic Glinn. Crew remains the standard angst-driven hero. There’s the requisite slovenly, boorish, yet brilliant computer genius and a less memorable supporting cast. New readers will struggle with minimal references to EES’s raison d'être and its fabled Quantitative Behavior Analysis. There’s diving lore, a précis on assembling a nuke, and a short, dense dissection of 'endoplasmic reticulum' and 'Golgi bodies' to conjecture a 'carbon-hydrogen-silicon-oxygen form of life' that seems to have no purpose other than the biological imperative.Science fiction as action adventure, the sort of book primed for screen treatment if a producer can find a sufficient F/X budget.", author: "Douglas Preston"}
]

books.each do |book|
  Book.create book
end
